### ISSUE TITLE
Change "(no/yes)" to "(y/n)"

### ISSUE THREAD

**Issue by Temerold** [ZynerSE/wdpDESKTOP-python#4]
Line 57, deps.py:

Please change:
ask_auto = input("Do you wan't automatic install of packages? (no/yes)") # Ask if user want's automatic packages install
to:
    ask_auto = input("Do you want automatic install of packages? (y/n)") # Ask if user want's automatic packages install

To be consistent.

**Comment by vermium-sifell** [comment]
Do it yourself.

**Comment by Temerold** [comment]
Fixed in "(y/n) consistency and corrected spelling error", https://github.com/ZynerSE/wdpDESKTOP-python/commit/dbffff60d31b7026692d6e39e7fa85ba6e869a38.

Thanks, me.
